### ISSUE TITLE
Why my issues were removed?

### ISSUE THREAD

**Issue by kingarthur72** [vfitoolkit/VFIToolkit-matlab#22] opened 2024-10-21 13:26 UTC
I have posted several issues with respect to the VFI models about portfolio choices. 

They are all gone? 

What happened?

**Comment by robertdkirkby** [comment] 2024-10-22 04:49
I commented on them and closed them. (Some fixes were pushed as part of addressing them.)

You can see the closed issues at:
https://github.com/vfitoolkit/VFIToolkit-matlab/issues?q=is%3Aissue+is%3Aclosed

(Or, if you click Issues, then at the top of the list of issues is grey text 'closed', and clicking that shows you all the closed issues)

**Comment by robertdkirkby** [comment] 2024-10-22 04:50
I am leaving this open for now to make sure you see it, but I will close it sometime in Nov if there is no further activity.

**Comment by robertdkirkby** [comment] 2024-10-22 04:52
PS. I think Github should have sent you notifications when I closed your issues. Notifications is the mailbox icon near top right of github website, there is a blue dot on it when you have unread notifications.

**Comment by robertdkirkby** [comment] 2024-10-23 03:40
Closing as essentially duplicate of:
https://github.com/vfitoolkit/IntroToLifeCycleModels/issues/6

**Closed by robertdkirkby** 2024-10-23 03:40 UTC
